# Generated by Django 4.1.2 on 2022-10-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('second_name', models.CharField(max_length=64)),
                ('birthday', models.DateTimeField()),
                ('root', models.BooleanField(default=False)),
            ],
        ),
    ]
