# Generated by Django 4.1.2 on 2022-11-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('root', models.BooleanField(default=False)),
            ],
        ),
    ]
