# Generated by Django 4.1.2 on 2022-11-03 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_commands_ideas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users2',
        ),
    ]
