# Generated by Django 4.1.3 on 2022-11-04 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_users2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='ideas',
            name='command_id',
        ),
        migrations.AddField(
            model_name='ideas',
            name='moderated',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='ideas',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='IdeasTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ideas')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tags')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorIdeas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idea_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ideas')),
            ],
        ),
    ]
