# Generated by Django 4.1.3 on 2022-11-04 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_categories_tags_remove_ideas_command_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideas',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.categories'),
        ),
    ]
