# Generated by Django 4.1.3 on 2022-11-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_ideas_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideas',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
