# Generated by Django 4.1.3 on 2022-11-05 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_ideas_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorCommands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('command_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.commands')),
            ],
        ),
    ]
